### ISSUE TITLE
Create new JavaScript code

### ISSUE THREAD

**Issue by Todd-Kridel** [Todd-Kridel/TK-Password-Generator#2]

**Comment by supsa-ak** [comment]
Hi, I can create a new javascript feature or solve a bug. I am participating in hacktoberfest.

**Comment by Todd-Kridel** [comment]
Hi. What is Hacktoberfest?

**Comment by Todd-Kridel** [comment]
p.s., How did you see my issue addition so quickly?

**Comment by supsa-ak** [comment]
I found your issue in github search.

It is open source contribution event https://hacktoberfest.com/

**Comment by Todd-Kridel** [comment]
Ah. Interesting. Thanks about the offer of help! However...I have to do all
of the coding of this particular repository because it is an assignment for
a class that I am doing.

**Comment by supsa-ak** [comment]
Ok, fine. I you want any help with new feature or solve bug ask me.

**Comment by Todd-Kridel** [comment]
Great! Thanks about that additional offer of help! I will keep you in-mind
for any coding problems that I encounter.
